#!/bin/bash

SETTINGS="/etc/arr_scripts"

###############################################################################

# load settings
if [ ! -f "${SETTINGS}" ]; then
  echo "❎ Settings-Datei nicht lesbar: ${SETTINGS}"
  exit 1
else
  source "${SETTINGS}"
fi

# sonarr api call function
BASE_URL="http://${SONARR_IP}:${SONARR_PORT}/api/v3"
sonarr_api() {
    local endpoint="$1"
    curl -s -H "X-Api-Key: $SONARR_APIKEY" "http://$SONARR_IP:$SONARR_PORT/api/v3/$endpoint"
}

# cycle through all ended tv shows
series_json=$(sonarr_api "series" )
echo "$series_json" | jq -r '.[] | select(.status=="ended") | .title + "|" + (.id|tostring)' | while IFS="|" read -r title id; do

    # get all episodes
    episodes_json=$(curl -s -G "${BASE_URL}/episode" --data-urlencode "seriesId=${id}" --data-urlencode "apikey=${SONARR_APIKEY}")
    
    # filter episodes (everything without airdate, except season 0)
    filtered_episodes=$(echo "$episodes_json" | jq -r '.[] | select(.seasonNumber != 0 and (.airDate == null or .airDate == "")) | "\(.seasonNumber|tostring) \(.episodeNumber|tostring) \(.title)"')
    
    # if episodes were found, list them
    if [[ -n "$filtered_episodes" ]]; then
        echo "$title"
        while read -r season episode ep_title; do
            # führende Nullen in Bash
            printf "    - S%02dE%02d: %s\n" "$season" "$episode" "$ep_title"
        done <<< "$filtered_episodes"
    fi
done
