#!/bin/bash

SETTINGS="/etc/arr_scripts"

###############################################################################

# load settings
if [ ! -f "${SETTINGS}" ]; then
  echo "❎ Settings-Datei nicht lesbar: ${SETTINGS}"
  exit 1
else
  source "${SETTINGS}"
fi

# sonarr api call function
BASE_URL="http://${SONARR_IP}:${SONARR_PORT}/api/v3"
sonarr_api() {
    local endpoint="$1"
    curl -s -H "X-Api-Key: $SONARR_APIKEY" "http://$SONARR_IP:$SONARR_PORT/api/v3/$endpoint"
}

# metafile check function
is_metadata_file() {
    local filename="$1"
    case "$filename" in
        banner.jpg|clearlogo.png|fanart.jpg|poster.jpg|tvshow.nfo) return 0 ;;
        season*-banner.jpg|season*-poster.jpg|season-specials-banner.jpg|season-specials-poster.jpg) return 0 ;;
        *) return 1 ;;
    esac
}

# cycle through all tv shows
series_json=$(sonarr_api "series")
echo "$series_json" | jq -c '.[]' | while read -r serie; do

  # get some metadata
  series_path=$(echo "$serie" | jq -r '.path')
  series_title=$(echo "$serie" | jq -r '.title')
  series_id=$(echo "$serie" | jq -r '.id')

  # ignore if path doesn't exist (i.e. has no files)
  if [ ! -d "$series_path" ]; then
      continue
  fi

  # cycle through all files in dir
  orphan_files=()
  known_files=$(sonarr_api "episodefile?seriesId=$series_id" | jq -r '.[].relativePath')
  while IFS= read -r file; do
        filename=$(basename "$file")

        # ignore metafiles files
        if is_metadata_file "$filename"; then
            continue
        fi

        # check if sonarr knows this file
        if ! echo "$known_files" | grep -Fxq "$filename"; then
            orphan_files+=("$filename")
        fi
    done < <(find "$series_path" -type f)

    # if there are orphans, list them
    if [ ${#orphan_files[@]} -gt 0 ]; then
        echo "$series_title:"
        for f in "${orphan_files[@]}"; do
            echo "    - $f"
        done
    fi

done
